language: php
php:
  - '5.6'
  - '7.0'
  
before_script:
  composer up
  
script: 
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml tests/
  
after_success:
  - travis_retry php vendor/bin/coveralls -v